inz.Server/ViewModels/Users/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace inz.Server.ViewModels.Users;

public record CreateViewModel
{
    [Required(ErrorMessage = "Proszę podać imię")]
    [Display(Name = "Imię")]
    public string Name { get; set; } = null!;

    [Required(ErrorMessage = "Proszę podać nazwisko")]
    [Display(Name = "Nazwisko")]
    public string Surname { get; set; } = null!;

    [Required(ErrorMessage = "Proszę podać adres email")]
    [EmailAddress(ErrorMessage = "Nieprawidłowy adres email")]
    public string Email { get; set; } = null!;

    [Required(ErrorMessage = "Proszę podać hasło")]
    [Display(Name = "Hasło")]
    public string Password { get; set; } = null!;

    [Required(ErrorMessage = "Potwierdź hasło")]
    [Compare("Password", ErrorMessage = "Hasła nie są zgodne")]
    [Display(Name = "Potwierdź hasło")]
    public string ConfirmPassword { get; set; } = null!;
}

inz.Server/ViewModels/Users/DeleteViewModel.cs
namespace inz.Server.ViewModels.Users;

public class DeleteViewModel
{
    public string Id { get; set; } = null!;
    public string NameSurname { get; set; } = null!;
}

inz.Server/ViewModels/Users/ResetPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace inz.Server.ViewModels.Users;

public class ResetPasswordViewModel
{
    public string UserId { get; set; } = null!;

    [Display(Name = "Użytkownik")]
    public string? NameSurname { get; set; } = null!;

    [Required(ErrorMessage = "Proszę podać nowe hasło")]
    [DataType(DataType.Password)]
    [Display(Name = "Nowe hasło")]
    public string NewPassword { get; set; } = null!;

    [Required(ErrorMessage = "Proszę powtórzyć nowe hasło")]
    [DataType(DataType.Password)]
    [Display(Name = "Potwierdź nowe hasło")]
    [Compare("NewPassword", ErrorMessage = "Hasła nie są zgodne.")]
    public string ConfirmPassword { get; set; } = null!;
}

inz.Server/ViewModels/Users/UserDetailsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace inz.Server.ViewModels.Users;

public class UserDetailsViewModel
{
    public string Id { get; set; } = null!;

    [Display(Name = "Imię")]
    public string Name { get; set; } = null!;

    [Display(Name = "Nazwisko")]
    public string Surname { get; set; } = null!;

    [Display(Name = "Adres Email")]
    public string Email { get; set; } = null!;

    [Display(Name = "Numer telefonu")]
    public string? PhoneNumber { get; set; }
}

inz.Server/Controllers/MvcControllers/UsersAdminController.cs
using inz.Server.Services;
using inz.Server.ViewModels.Users;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace inz.Server.Controllers.MvcControllers;

[Authorize(Roles = "Admin", AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
[Route("Admin/Users")]
public class UsersAdminController : Controller
{
    private readonly IUsersService _users;

    public UsersAdminController(IUsersService users)
    {
        _users = users;
    }

    [HttpGet("")]
    public async Task<IActionResult> Index(string? search, int? page)
    {
        const int pageSize = 20;
        var currentPage = page ?? 1;
        currentPage = currentPage < 1 ? 1 : currentPage;

        var dto = await _users.GetUsers(search, currentPage, pageSize);
        var model = new IndexViewModel
        {
            Users = dto.Users,
            Search = search,
            Page = currentPage,
            TotalPages = dto.TotalPages
        };

        return View(model);
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> UserDetails(string id)
    {
        var res = await _users.GetUser(id);
        if (res.IsFailure) return NotFound();

        var user = res.Value;
        var model = new UserDetailsViewModel
        {
            Id = user.Id,
            Name = user.Name,
            Surname = user.Surname,
            Email = user.Email,
            PhoneNumber = user.Phone
        };
        return View(model);
    }

    [HttpGet("Create")]
    public IActionResult Create()
    {
        var model = new CreateViewModel();
        return View(model);
    }

    [HttpPost("Create")]
    public async Task<IActionResult> Create(CreateViewModel model)
    {
        if (!ModelState.IsValid) return View(model);

        var res = await _users.CreateUser(model);
        if (res.IsSuccess)
        {
            TempData["SuccessMessage"] = $"Pomyślnie utworzono użytkownika {model.Email}.";
            return RedirectToAction("Index");
        }

        switch (res.Error)
        {
            case AppErrors.DuplicateUserName e:
                ModelState.AddModelError(nameof(model.Email), e.Message);
                break;

            case AppErrors.InvalidPasswordError e:
                ModelState.AddModelError(nameof(model.Password), e.Message);
                break;

            case AppErrors.GenericError e:
                ModelState.AddModelError(string.Empty, e.Message);
                break;
        }

        return View(model);
    }

    [HttpGet("Edit/{id}")]
    public async Task<IActionResult> Edit(string id, string? returnUrl = null)
    {
        var res = await _users.GetUser(id);
        if (res.IsFailure) return NotFound(res.Error!.Message);
        var user = res.Value;
        var model = new EditUserViewModel
        {
            Id = user.Id,
            Name = user.Name,
            Surname = user.Surname,
            Email = user.Email,
            ReturnUrl = returnUrl
        };

        return View(model);
    }

    [HttpPost("Edit/{id}")]
    public async Task<IActionResult> Edit(string id, EditUserViewModel model)
    {
        if (id != model.Id) return BadRequest();
        if (!ModelState.IsValid) return View(model);

        var res = await _users.UpdateUser(model);
        if (res.IsSuccess)
        {
            TempData["SuccessMessage"] = $"Pomyślnie zedytowano użytkownika {model.Name} {model.Surname}.";
            return RedirectToAction("Index");
        }

        switch (res.Error)
        {
            case AppErrors.DuplicateUserName e:
                ModelState.AddModelError(nameof(model.Email), e.Message);
                break;

            case AppErrors.GenericError e:
                ModelState.AddModelError(string.Empty, e.Message);
                break;
        }

        return View(model);
    }

    [HttpGet("Delete/{id}")]
    public async Task<IActionResult> Delete(string id)
    {
        var res = await _users.GetUser(id);
        if (res.IsFailure) return NotFound();

        var user = res.Value;
        var model = new DeleteViewModel
        {
            Id = user.Id,
            NameSurname = $"{user.Name} {user.Surname}"
        };
        return PartialView("_Delete", model);
    }

    [HttpPost("Delete/{id}")]
    public async Task<IActionResult> Delete(string id, DeleteViewModel model)
    {
        await _users.DeleteUser(id);
        TempData["SuccessMessage"] = $"Pomyślnie usunięto użytkownika {model.NameSurname}";
        return RedirectToAction("Index");
    }

    [HttpGet("ResetPassword/{id}")]
    public async Task<IActionResult> ResetPassword(string id)
    {
        var res = await _users.GetUser(id);
        if (res.IsFailure) return NotFound();

        var user = res.Value;
        var viewModel = new ResetPasswordViewModel
        {
            UserId = user.Id,
            NameSurname = $"{user.Name} {user.Surname}"
        };

        return View(viewModel);
    }

    [HttpPost("ResetPassword/{id}")]
    public async Task<IActionResult> ResetPassword(string id, ResetPasswordViewModel model)
    {
        if (!ModelState.IsValid) return View(model);
        var res = await _users.ChangePassword(id, model.NewPassword);
        if (res.IsSuccess)
        {
            TempData["SuccessMessage"] = $"Pomyślnie zmieniono hasło dla {model.NameSurname}";
            return RedirectToAction("UserDetails", new { id = model.UserId });
        }

        switch (res.Error)
        {
            case AppErrors.InvalidPasswordError e:
                ModelState.AddModelError(nameof(model.NewPassword), e.Message);
                break;

            case AppErrors.GenericError e:
                ModelState.AddModelError(string.Empty, e.Message);
                break;
        }

        return View(model);
    }
}

inz.Server/Views/UsersAdmin/Create.cshtml
@model inz.Server.ViewModels.Users.CreateViewModel

@{
    ViewBag.Title = "Dodaj użytkownika";
    Layout = "_AdminLayout";
}

<h2>Dodaj nowego użytkownika</h2>
<hr />

<div class="row">
    <div class="col-md-7">
        <form asp-action="Create" method="post">
            
            <div asp-validation-summary="ModelOnly" class="alert alert-danger" role="alert"></div>

            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Surname" class="form-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Email" class="form-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Password" class="form-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="ConfirmPassword" class="form-label"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            
            <div class="mt-4">
                <button type="submit" class="btn btn-primary">Zapisz</button>
                <a asp-action="Index" class="btn btn-outline-secondary">Anuluj</a>
            </div>
        </form>
    </div>
</div>

inz.Server/Views/UsersAdmin/Edit.cshtml
@model inz.Server.ViewModels.Users.EditUserViewModel

@{
    ViewBag.Title = "Edytuj użytkownika";
    Layout = "_AdminLayout";
}

<h2 class="mb-4">Edytuj użytkownika</h2>

<div class="card shadow-sm">
    <div class="card shadow-sm">
        <form asp-action="Edit" asp-route-id="@Model.Id" method="post">
            <div class="card-body">
                <div asp-validation-summary="ModelOnly" class="alert alert-danger" role="alert"></div>

                <input type="hidden" asp-for="ReturnUrl"/>
                <input type="hidden" asp-for="Id"/>

                <div class="mb-3">
                    <label asp-for="Name" class="form-label"></label>
                    <input asp-for="Name" class="form-control"/>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Surname" class="form-label"></label>
                    <input asp-for="Surname" class="form-control"/>
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Email" class="form-label"></label>
                    <input asp-for="Email" class="form-control"/>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="card-footer text-end">
                @if (!string.IsNullOrEmpty(Model.ReturnUrl) && Url.IsLocalUrl(Model.ReturnUrl))
                {
                    <a href="@Model.ReturnUrl" class="btn btn-outline-secondary">Anuluj</a>
                }
                else
                {
                    <a asp-action="Index" class="btn btn-outline-secondary">Anuluj</a>
                }
                <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
            </div>
        </form>
    </div>
</div>

inz.Server/Views/UsersAdmin/Index.cshtml
@model inz.Server.ViewModels.Users.IndexViewModel

@{
    ViewBag.Title = "Użytkownicy";
    Layout = "_AdminLayout";
}

<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="mb-0">Pracownicy</h1>

    <a asp-controller="UsersAdmin" asp-action="Create" class="btn btn-primary">
        <i class="bi bi-plus-circle-fill me-2"></i>Dodaj nowego pracownika
    </a>
</div>


<form asp-controller="UsersAdmin" asp-action="Index" method="get" class="mb-4">
    <div class="input-group">
        <input type="text" asp-for="Search" class="form-control" placeholder="Szukaj po imieniu lub nazwisku...">
        <button type="submit" class="btn btn-primary">
            <i class="bi bi-search"></i> Szukaj
        </button>
        <a asp-action="Index" class="btn btn-secondary" title="Wyczyść filtry"><i class="bi bi-x-lg"></i></a>
    </div>
</form>

<div class="card shadow-sm">
    <div class="card-body">
        <table class="table table-hover align-middle">
            <thead>
            <tr>
                <th>Imię</th>
                <th>Nazwisko</th>
                <th>Email</th>
                <th style="width: 1%;" class="text-end">Akcje</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var user in Model.Users)
            {
                <tr>
                    <td>@user.Name</td>
                    <td>@user.Surname</td>
                    <td>@user.Email</td>
                    <td class="text-end">
                        <div class="btn-group" role="group">
                            <a asp-controller="UsersAdmin" asp-action="UserDetails" asp-route-id="@user.Id"
                               class="btn btn-sm btn-outline-secondary">Szczegóły</a>
                            <a asp-controller="UsersAdmin" asp-action="Edit" asp-route-id="@user.Id"
                               asp-route-returnUrl="@(Context.Request.Path + Context.Request.QueryString)"
                               class="btn btn-sm btn-outline-secondary">Edytuj</a>
                            <a href="@Url.Action("Delete", "UsersAdmin", new { id = user.Id })"
                               class="btn btn-sm btn-outline-danger" data-bs-toggle="ajax-modal"
                               data-bs-target="#deleteUserModal">Usuń</a>
                        </div>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

@if (Model.TotalPages > 1)
{
    <nav class="mt-3">
        <ul class="pagination justify-content-end">

            <li class="page-item @(Model.Page == 1 ? "disabled" : "")">
                <a class="page-link" asp-action="Index"
                   asp-route-page="@(Model.Page - 1)"
                   asp-route-searchString="@Model.Search">Poprzednia</a>
            </li>

            @for (var i = 1; i <= Model.TotalPages; i++)
            {
                <li class="page-item @(i == Model.Page ? "active" : "")">
                    <a class="page-link" asp-action="Index"
                       asp-route-page="@i"
                       asp-route-searchString="@Model.Search">@i</a>
                </li>
            }

            <li class="page-item @(Model.Page == Model.TotalPages ? "disabled" : "")">
                <a class="page-link" asp-action="Index"
                   asp-route-page="@(Model.Page + 1)"
                   asp-route-searchString="@Model.Search">Następna</a>
            </li>

        </ul>
    </nav>
}

inz.Server/Views/UsersAdmin/ResetPassword.cshtml
@model inz.Server.ViewModels.Users.ResetPasswordViewModel

@{
    ViewData["Title"] = "Resetowanie hasła";
    Layout = "_AdminLayout";
}

<h1 class="mb-4">Resetowanie Hasła</h1>

<div class="card shadow-sm">
    <div class="card-header">
        <h5 class="mb-0">Użytkownik: <span class="text-primary">@Model.NameSurname</span></h5>
    </div>
    <form asp-controller="UsersAdmin" asp-action="ResetPassword" asp-route-id="@Model.UserId" method="post">
        <div class="card-body">
            <div class="row">
                <div class="col-md-7">
                    <input type="hidden" asp-for="UserId"/>
                    <input type="hidden" asp-for="NameSurname"/>

                    <div asp-validation-summary="ModelOnly" class="alert alert-danger" role="alert"></div>

                    <div class="mb-3">
                        <label asp-for="NewPassword" class="form-label"></label>
                        <input asp-for="NewPassword" class="form-control"/>
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ConfirmPassword" class="form-label"></label>
                        <input asp-for="ConfirmPassword" class="form-control"/>
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>


                </div>
            </div>
        </div>
        <div class="card-footer text-end">
            <a asp-controller="UsersAdmin" asp-action="UserDetails" asp-route-id="@Model.UserId"
               class="btn btn-outline-secondary">Anuluj</a>
            <button type="submit" class="btn btn-warning">Zresetuj Hasło</button>
        </div>
    </form>
</div>

inz.Server/Views/UsersAdmin/UserDetails.cshtml
@model inz.Server.ViewModels.Users.UserDetailsViewModel

@{
    ViewBag.Title = $"Szczegóły - {Model.Name} {Model.Surname}";
    Layout = "_AdminLayout";
}


<h1 class="mb-4">Szczegóły Użytkownika</h1>

<div class="card shadow-sm">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Podstawowe dane</h5>
        <div>
            <a asp-controller="UsersAdmin" asp-action="ResetPassword" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-warning">
                <i class="bi bi-key-fill me-2"></i>Resetuj hasło
            </a>
            <a asp-action="Edit" asp-route-id="@Model.Id"
               asp-route-returnUrl="@(Context.Request.Path + Context.Request.QueryString)"
               class="btn btn-sm btn-outline-primary">
                <i class="bi bi-pencil-fill me-2"></i>Edytuj
            </a>
            <a asp-action="Index" class="btn btn-sm btn-secondary">
                <i class="bi bi-arrow-left-circle me-2"></i>Wróć do listy
            </a>
        </div>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Name)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Name)</dd>

            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Surname)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Surname)</dd>

            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.Email)</dt>
            <dd class="col-sm-9">@Html.DisplayFor(model => model.Email)</dd>

            <dt class="col-sm-3">@Html.DisplayNameFor(model => model.PhoneNumber)</dt>
            <dd class="col-sm-9">@(string.IsNullOrEmpty(Model.PhoneNumber) ? "Nie podano" : Model.PhoneNumber)</dd>
        </dl>
    </div>
</div>

inz.Server/Views/UsersAdmin/_Delete.cshtml
@model inz.Server.ViewModels.Users.DeleteViewModel

<div class="modal fade" id="deleteUserModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteUserModalLabel">Potwierdź Usunięcie</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                Czy na pewno chcesz usunąć użytkownika <strong>@Model.NameSurname</strong>?
                <br />
                Tej operacji nie można cofnąć.
            </div>
            <div class="modal-footer">
                <form asp-controller="UsersAdmin" asp-action="Delete" asp-route-id="@Model.Id" method="post">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Anuluj</button>
                    <button type="submit" class="btn btn-danger">Usuń</button>
                </form>
            </div>
        </div>
    </div>
</div>